export const UTENSILS = [
  "horno",
  "licuadora",
  "sarten",
  "olla",
  "microondas",
  "estufa de gas",
  "estufa electrica",
  "parrilla",
  "batidora",
  "freidora de aire",
  "olla de presion",
  "vaporera",
  "wok",
  "procesador",
  "cuchillo",
  "tabla de cortar",
];

export const CUISINES = [
  { label: "Sin preferencia", value: "" },
  { label: "Mexico", value: "mexican" },
  { label: "Italia", value: "italian" },
  { label: "China", value: "chinese" },
  { label: "Japon", value: "japanese" },
  { label: "India", value: "indian" },
  { label: "Tailandia", value: "thai" },
  { label: "Francia", value: "french" },
  { label: "Mediterranea", value: "mediterranean" },
  { label: "Estados Unidos", value: "american" },
  { label: "Brasil", value: "brazilian" },
  { label: "Canada", value: "canadian" },
  { label: "Caribe", value: "caribbean" },
  { label: "Marruecos", value: "moroccan" },
  { label: "Grecia", value: "greek" },
  { label: "Vietnam", value: "vietnamese" },
  { label: "Corea", value: "korean" },
  { label: "Espana", value: "spanish" },
];

export const COMMON_INGREDIENTS = [
  "tomate",
  "cebolla",
  "ajo",
  "chile",
  "cilantro",
  "limon",
  "zanahoria",
  "papa",
  "calabaza",
  "brocoli",
  "espinaca",
  "lechuga",
  "aguacate",
  "champinon",
  "maiz",
  "arroz",
  "pasta",
  "tortilla",
  "pan",
  "avena",
  "frijol",
  "lenteja",
  "garbanzo",
  "pollo",
  "carne",
  "res",
  "cerdo",
  "pescado",
  "atun",
  "camaron",
  "huevo",
  "queso",
  "leche",
  "yogurt",
  "crema",
  "mantequilla",
  "aceite de oliva",
  "salsa de soya",
  "miel",
  "nuez",
  "almendra",
  "cafe",
  "te",
  "agua mineral",
  "vino",
  "cerveza",
];
